#!/bin/bash

set -e

_C_STANDARD=11 # c standard
_O_LEVEL=3 # optim

# basic
_COMPILE_OPTIONS="-Wall -Wextra"
_COMPILE_OPTIONS="${_COMPILE_OPTIONS} -std=c${_C_STANDARD}"
_COMPILE_OPTIONS="${_COMPILE_OPTIONS} -O${_O_LEVEL}"

_COMPILE_OPTIONS="${_COMPILE_OPTIONS} -flto -Wl,-z,now -Wl,-z,relro -Wl,--build-id=none"

# made to suppress GLFW warnings which are inevitable
_COMPILE_OPTIONS="${_COMPILE_OPTIONS} -Wno-unused-parameter"

# libs
_COMPILE_OPTIONS="-lwinmm -lgdi32 -lopengl32"
detected_OS="$(shell uname 2>/dev/null || echo Unknown)"

if [[ "${detected_OS}" == "Darwin" ]]; then       # Mac OS X
	_COMPILE_OPTIONS="-lm -framework Foundation -framework AppKit -framework OpenGL -framework CoreVideo"
fi
if [[ "${detected_OS}" == "Linux" ]]; then
	_COMPILE_OPTIONS="-lXrandr -lX11 -lm -lGL -ldl -lpthread"
fi


_SOURCES="demo-6624.c"

echo "Running:"
echo "    gcc ${_COMPILE_OPTIONS} ${_SOURCES} -o demo-6624"

gcc ${_SOURCES} ${_COMPILE_OPTIONS} -o demo-6624
echo "filesize after build: $(wc -c demo-6624)"

# excessive stripping like oh my god
strip -R .comment demo-6624
strip -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag demo-6624
strip --remove-section=.jcr --remove-section=.got.plt demo-6624
strip --remove-section=.eh_frame --remove-section=.eh_frame_ptr --remove-section=.eh_frame_hdr demo-6624
echo "filesize after strip: $(wc -c demo-6624)"
